name = "MultipleTesting"
uuid = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
license = "MIT"
authors = "Julian Gehring"
repository = "https://github.com/juliangehring/MultipleTesting.jl"
version = "0.5.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.22 - 0.25"
SpecialFunctions = "1.0, 2"
StatsBase = "0.32 - 0.33, 0.34"
julia = "1.4"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
